basePath: /
definitions:
  models.EnlistmentRequest:
    description: Request parameters for scaling an enlistment
    properties:
      enlistment:
        example: |-
          Item 1: 1 year
          Item2: 1 month
        type: string
      scale:
        example: 1 minute
        type: string
    type: object
  models.EnlistmentResponse:
    description: Response containing scaled enlistment values
    properties:
      scaled:
        example:
        - '["Item 1: 1 minute"'
        - '"Item 2: 5 seconds"]'
        items:
          type: string
        type: array
    type: object
  models.HealthResponse:
    description: Service health information
    properties:
      ready:
        type: boolean
      starttime:
        type: string
      timestamp:
        type: string
      uptime:
        type: number
      version:
        type: string
    type: object
  models.UnitJSON:
    description: A unit with value and available aliases
    properties:
      aliases:
        items:
          type: string
        type: array
      name:
        type: string
      value:
        type: number
    type: object
  models.VersionResponse:
    description: Service version information
    properties:
      version:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: adrian.grzemski@gmail.com
    name: Adrian Grzemski
  description: This is a service for refscaler app
  license:
    name: MIT
  title: RefScaler
  version: 1.0.0
paths:
  /health:
    get:
      description: Returns the current health status of the service
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.HealthResponse'
      summary: Get service health
      tags:
      - general
  /scale:
    post:
      consumes:
      - application/json
      description: Scales an enlistment based on the provided scale factor
      parameters:
      - description: Enlistment scale request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.EnlistmentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.EnlistmentResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Scale an enlistment
      tags:
      - scaler
  /units:
    get:
      description: Returns all available units in the registry
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            description: A list of unit groups
            items:
              type: string
            type: array
      summary: Get all units
      tags:
      - units
  /units/{name}:
    get:
      description: Returns a specific unit group by its name
      parameters:
      - description: Unit group name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            description: A list of units representing a group
            items:
              $ref: '#/definitions/models.UnitJSON'
            type: array
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get unit by name
      tags:
      - units
  /version:
    get:
      description: Returns the current version of the service
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.VersionResponse'
      summary: Get service version
      tags:
      - general
swagger: "2.0"
