{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "refscaler.fullname" . }}-tls-redirect
  labels:
    {{- include "refscaler.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: {{ .Values.gateway.gatewayName }}
    namespace: {{ .Values.gateway.gatewayNamespace }}
    sectionName: {{ .Values.gateway.httpSectionName }}
  hostnames:
  - {{ .Values.gateway.hostname | quote }}
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        port: 301
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "refscaler.fullname" . }}-route
  labels:
    {{- include "refscaler.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: {{ .Values.gateway.gatewayName }}
    namespace: {{ .Values.gateway.gatewayNamespace }}
    sectionName: {{ .Values.gateway.httpsSectionName }}
  hostnames:
  - {{ .Values.gateway.hostname | quote }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: {{ .Values.gateway.apiPathPrefix | default "/api" }}
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: "/"
    backendRefs:
    - name: {{ include "refscaler.fullname" . }}-backend
      port: {{ .Values.backend.service.port }}
  - matches:
    - path:
        type: PathPrefix
        value: "/swagger"
    backendRefs:
    - name: {{ include "refscaler.fullname" . }}-backend
      port: {{ .Values.backend.service.port }}
{{- end }}
