{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "refscaler.fullname" . }}-frontend-route
  labels:
    {{- include "refscaler.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: {{ .Values.gateway.gatewayName }}
    namespace: {{ .Values.gateway.gatewayNamespace }}
    sectionName: {{ .Values.gateway.httpsSectionName }}
  hostnames:
  - {{ .Values.gateway.hostname | quote }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ include "refscaler.fullname" . }}-frontend
      port: {{ .Values.frontend.service.port }}
{{- end }}
